crm01/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    # 注册登录重置密码
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^reset_psd/', views.reset_psd, name='reset_psd'),
    url(r'^get_cverification_code/', views.get_cverification_code, name='get_cverification_code'),

    # 首页
    url(r'^base/', views.base, name='base'),

    # 公户/私户:获取/查询/批量处理（一个页面版本）
    url(r'^customer/$', views.Public_Private_Customers.as_view(), name='customers'),
    url(r'^mycustomer/$', views.Public_Private_Customers.as_view(), name='mycustomers'),

    # 客户添加/编辑操作（一个页面版本）
    url(r'^customer/add/', views.Add_Edit_Customer.as_view(), name='addcustomer'),
    url(r'^mycustomer/add/', views.Add_Edit_Customer.as_view(), name='addmycustomer'),

    url(r'^customer/edit/(\d+)/', views.Add_Edit_Customer.as_view(), name='editcustomer'),
    url(r'^mycustomer/edit/(\d+)/', views.Add_Edit_Customer.as_view(), name='editmycustomer'),

    # 公户/私户删除操作
    url(r'^customer/delete/(\d+)/', views.Deletecustomer.as_view(), name='deletecustomer'),
    url(r'^mycustomer/delete/(\d+)/', views.Deletecustomer.as_view(), name='deletemycustomer'),

    # 跟进记录
    url(r'^followrecord/$', views.Followrecord.as_view(), name='followrecord'),
    # 添加/编辑跟进记录（一个页面版本）
    url(r'^followrecord/add/', views.Add_Edit_Followrecord.as_view(), name='addfollowrecord'),
    url(r'^followrecord/edit/(\d+)/', views.Add_Edit_Followrecord.as_view(), name='editfollowrecord'),
    # 跟进记录删除，详情
    url(r'^followrecord/delete/(\d+)/', views.DeleteFollowrecord.as_view(), name='deletefollowrecord'),
    url(r'^followrecord/more/(\d+)/', views.Followrecord.as_view(), name='morefollowrecord'),

    # 学生信息
    url(r'^student/$', views.Student.as_view(), name='student'),
    url(r'^student/add/', views.Add_Edit_Student.as_view(), name='addstudent'),
    url(r'^student/edit/(\d+)/', views.Add_Edit_Student.as_view(), name='editstudent'),
    url(r'^student/delete/(\d+)/', views.DeleteStudent.as_view(), name='deletestudent'),

    # 教学信息
    url(r'^teach/$', views.Teach.as_view(), name='teach'),
    url(r'^teach/add/', views.Add_Edit_Teach.as_view(), name='addteach'),
    url(r'^teach/edit/(\d+)/', views.Add_Edit_Teach.as_view(), name='editteach'),
    url(r'^teach/delete/(\d+)/', views.DeleteTeach.as_view(), name='deleteteach'),

    # 学习情况详情(批量操作：原生版和formset版)
    url(r'^studydetail/(\d+)', views.Studydetail.as_view(), name='studydetail'),

    # 学习信息
    url(r'^study/$', views.Study.as_view(), name='study'),
    url(r'^study/add/', views.Add_Edit_Study.as_view(), name='addstudy'),
    url(r'^study/edit/(\d+)/', views.Add_Edit_Study.as_view(), name='editstudy'),
    url(r'^study/delete/(\d+)/', views.DeleteStudy.as_view(), name='deletestudy'),
    url(r'^study/more/(\d+)/', views.Study.as_view(), name='morestudy'),

    # 用户信息管理
    url(r'^user/list/$', views.UserList.as_view(), name='user_list'),
    url(r'^user/add/', views.Add_Edit_User.as_view(), name='user_add'),
    url(r'^user/edit/(\d+)/', views.Add_Edit_User.as_view(), name='user_edit'),
    url(r'^user/delete/(\d+)/', views.DeleteUser.as_view(), name='user_delete'),
    url(r'^userpwd_ret/(\d+)/', views.userpwd_ret, name='userpwd_ret'),

    # 角色信息管理
    url(r'^role/list/$', views.RoleList.as_view(), name='role_list'),
    url(r'^role/add/', views.Add_Edit_Role.as_view(), name='role_add'),
    url(r'^role/edit/(\d+)/', views.Add_Edit_Role.as_view(), name='role_edit'),
    url(r'^role/delete/(\d+)/', views.DeleteRole.as_view(), name='role_delete'),
    url(r'^user/list/role/$', views.UserList.as_view(), name='user_list_role'),

    # 权限信息管理
    url(r'^permission/list/$', views.PermissionList.as_view(), name='permission_list'),
    url(r'^permission/add/', views.Add_Edit_Permission.as_view(), name='permission_add'),
    url(r'^permission/edit/(\d+)/', views.Add_Edit_Permission.as_view(), name='permission_edit'),
    url(r'^permission/delete/(\d+)/', views.DeletePermission.as_view(), name='permission_delete'),

    # 菜单信息管理
    url(r'^menu/list/$', views.MenuList.as_view(), name='menu_list'),
    url(r'^menu/add/', views.Add_Edit_Menu.as_view(), name='menu_add'),
    url(r'^menu/edit/(\d+)/', views.Add_Edit_Menu.as_view(), name='menu_edit'),
    url(r'^menu/delete/(\d+)/', views.DeleteMenu.as_view(), name='menu_delete'),
    url(r'^permission/list/menu/$', views.PermissionList.as_view(), name='permission_list_menu'),

    # 权限分配
    url(r'^permission/distribute/$', views.PermissionDistribute.as_view(), name='permission_distribute'),


]

app01/models.py
# Create your models here.

from django.contrib.auth.models import AbstractUser

from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
# 安装:pip install django-multiselectfield,针对choices多选用的


from django.utils.safestring import mark_safe

# 课程选项
course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

# 学习方式选项
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

# 客户途径
source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

# 跟进记录状态
seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)

pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

# 考勤选项
attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

# 课程选项
score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


# 用户表（自定义使用auth认证）
class UserInfo(AbstractUser):
    # 销售,班主任,讲师,三哥
    telephone = models.CharField(max_length=32, null=True, blank=True, verbose_name='联系电话')
    role = models.ManyToManyField(to='Role', verbose_name='角色', default=None, null=True, blank=True)
    dep = models.ForeignKey(to='Department', null=True, blank=True)


# 角色表
class Role(models.Model):
    name = models.CharField(max_length=32, verbose_name='角色', unique=True)
    permission = models.ManyToManyField(to='Permission', verbose_name='权限', null=True, blank=True)

    def __str__(self):
        return self.name


# 权限表
class Permission(models.Model):
    name = models.CharField(verbose_name='操作权限', max_length=32)
    url = models.CharField(max_length=48, verbose_name='url路径')
    # menu=models.BooleanField(default=False,verbose_name='是否为菜单')
    # ico=models.CharField(max_length=32,verbose_name='图标',default='fa fa-link')
    menu = models.ForeignKey(to='Menu', null=True, blank=True)  # 设置权限显示菜单归属于一级菜单的id,不为空的即为要显示的二级菜单
    pid = models.ForeignKey(to='self', null=True, blank=True)  # 不同权限归属的显示菜单

    def __str__(self):
        return self.name


# 一级菜单表
ico_list = ['fa fa-mortar-board', 'fa fa-link', 'fa fa-map-o', 'fa fa-reorder', 'fa fa-sliders', 'fa fa-bandcamp',
            'fa fa-ravelry', 'fa fa-user-circle', 'fa fa-window-restore', 'fa fa-window-maximize',
            'fa fa-window-restore',
            'fa fa-book', 'fa fa-bookmark-o', 'fa fa-cubes', 'fa fa-folder-open-o', 'fa fa-laptop', 'fa fa-server',
            'fa fa fa-address-card','fa fa-sitemap','fa fa-sticky-note-o','fa fa-tasks','fa fa-bar-chart-o','fa fa-columns',
            'fa fa-list-ul','fa fa-indent']


class Menu(models.Model):
    name = models.CharField(max_length=12, verbose_name='一级菜单')
    ico = models.CharField(max_length=32, verbose_name='一级菜单图标', default='fa fa-link')

    def __str__(self):
        return self.name


# 部门表
class Department(models.Model):
    '''
    部门表
    '''
    name = models.CharField(max_length=12, verbose_name='部门名称')
    count = models.IntegerField(verbose_name='部门人数')

    def __str__(self):
        return self.name


# 客户表
class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True,
                           null=True)  # 存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True, max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True,
                                       null=True)  # self指的就是自己这个表，和下面写法是一样的效果

    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)  # 多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")  # help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)  # 考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)  # 销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    # 用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True)

    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", null=True,
                                        blank=True)  # blank在ModelForm校验是或否允许为空，null是数据库判断

    def __str__(self):
        return self.name + ":" + self.qq  # 主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。

    def get_classlist(self):  # 当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l = []
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l)  # 纯文本，不用mark_safe也可以昂


# 校区表
class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


# 班级表
class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")  # python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)  # 不一定什么时候结业，哈哈，所以可为空

    # contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo',
                                      verbose_name="老师")  # 对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


# 跟进记录表
class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")

    note = models.TextField(verbose_name="跟进内容...")

    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")

    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')

    date = models.DateTimeField("跟进日期", auto_now_add=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


# 报名表
class Enrollment(models.Model):
    """
    报名表
    """

    customer = models.ForeignKey('Customer', verbose_name='客户名称')

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)

    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)

    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")

    memo = models.TextField('备注', blank=True, null=True)

    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    school = models.ForeignKey('Campuses')  # 校区表

    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


# 学生表
class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer', on_delete=models.CASCADE, null=True, blank=True)

templates/add_edit_student.html
{% extends 'base.html' %}



<!--右边内容标题-->
{% block title %}
    <h1>
        {% if flag %}
            添加学生信息
            <small>Edit Customers</small>
        {% else %}
            编辑学生信息
            <small>Add Customers</small>
        {% endif %}
    </h1>
{% endblock %}


<!--右边内容部分-->
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-xs-offset-2">
                <form action="" method="post" novalidate class="form-horizontal">

                    {% for field in student_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-3 control-label">{{ field.label }}</label>
                            <div class="col-xs-9">

                                {{ field }}

                                <p class="text-danger"> {{ field.errors.0 }}</p>
                            </div>
                        </div>
                    {% endfor %}
                    {% csrf_token %}
                    <br><input type="submit" class="btn btn-success pull-right">
                </form>
            </div>
        </div>
    </div>



{% endblock %}

{% block js %}

    <script>
    //编辑时禁用学生选项
        if (! {{ flag }}){
            $('#id_customer').attr('onmousedown','return false')
        }
    </script>
{% endblock %}

templates/public_private_customers.html
{% extends 'base.html' %}
{% load static %}
{% load permission %}

<!--右边内容标题-->
{% block title %}
    <h1>
        {% if flag %}
            我的客户
            <small>Private Customers</small>
        {% else %}
            公共客户
            <small>Public Customers</small>
        {% endif %}


    </h1>

    <div class="row" style="margin-top: 15px;">

        <!--添加客户-->

        {% if flag %}
            {% if 'addmycustomer'|permission_noarg:request %}
                <a href="{% url 'addmycustomer' %}" class="btn btn-info btn-sm  col-xs-1 fa fa-user-plus "
                   style="margin-left: 30px;height:28px" title="添加客户">添加客户</a>
            {% endif %}
        {% else %}
            {% if 'addcustomer'|permission_noarg:request %}
                <a href="{% url 'addcustomer' %}" class="btn btn-info btn-sm  col-xs-1 fa fa-user-plus "
                   style="margin-left: 30px;height:28px" title="添加客户">添加客户</a>
            {% endif %}
        {% endif %}



        <!--批量操作:post请求当前路径-->
        {% if 'editcustomer'|permission_arg:request or 'editmycustomer'|permission_arg:request %}<!--判断当前用户是否有权限，自定义过滤器
            -->


            <div class="col-xs-6">
                <!--批量操作选项-->
                <select name="batch_operation" id="operation" style="height: 26px;">
                    <option value="">--操作--</option>
                    <option value="batch_delete">批量删除</option>
                    <option value="batch_update">批量修改</option>
                    {% if flag %}
                        <option value="batch_private_public">私户转公户</option>
                    {% else %}
                        <option value="batch_public_private">公户转私户</option>
                    {% endif %}


                </select>

                <!--批量更新字段选择-->
                <select name="" id="fields" style="height: 26px;" hidden="hidden">
                    {% for field in allfields %}
                        {% if field.name in batch_update_fields_list %}
                            <option value="{{ field.name }}">{{ field.label }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <!--更新值选择-->

                {% for field in allfields %}
                    {% if field.name in batch_update_fields_list %}
                        <div id="{{ field.name }}" hidden class="c1 "
                             style="width:180px;height: 26px;margin-bottom: 10px">{{ field }}</div>
                    {% endif %}
                {% endfor %}


                {% csrf_token %}
                <button class="btn btn-danger" style="height: 26px;line-height: 12px;vertical-align: 0.5px"
                        id="batch_operation">Go
                </button>

            </div>
        {% endif %}

        <!--查询字段-->
        <form action="" class=" col-xs-2 pull-right " method="get" style="padding-right: 0" novalidate>
            <select name="field" id="search" style="height: 25px;">
                <option value="">--字段--</option>
                {% for field in allfields %}
                    {% if field.name in search_fields_list %}
                        <option value="{{ field.name }}">{{ field.label }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <input type="submit" value="查询">


            {% for field in allfields %}
                {% if field.name in search_fields_list %}
                    <div class="c2 {{ field.name }}" id="{{ field.name }}" hidden
                         style="width: 126px;">{{ field }}</div>
                {% endif %}
            {% endfor %}


        </form>


    </div>

{% endblock %}


<!--右边内容部分-->
{% block content %}



    <table class="table table-hover table-bordered table-responsive tab-content text-center">
        <thead>
        <tr>
            <th>
                <button class="btn btn-xs btn-primary" id="all" title="全选"><i class="fa fa-check-square-o"></i></button>
                <button class="btn btn-xs btn-success" id="opp" title="反选"><i class="fa fa-check-square"></i></button>


            <th>序号</th>
            <th>姓名</th>
            <th>性别</th>
            <th>客户来源</th>
            <th>QQ</th>
            <th>咨询课程</th>
            <th>状态</th>
            <th>已报班级</th>
            <th>销售</th>
            {% if 'morefollowrecord'|permission_arg:request %}
                <th>跟进</th>
            {% endif %}
            {% if 'editmycustomer'|permission_arg:request or 'editcustomer'|permission_arg:request or 'deletemycustomer'|permission_arg:request or 'deletecustomer'|permission_arg:request %}
                <th>操作</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for customer_obj in customer_objs %}
            <tr>
                <td><input type="checkbox" name="select" value="{{ customer_obj.pk }}"></td>
                <td>{{ forloop.counter }}</td>
                <td>{{ customer_obj.name }}</td>
                <td>{{ customer_obj.get_sex_display }}</td>
                <td>{{ customer_obj.get_source_display }}</td>
                <td>{{ customer_obj.qq }}</td>

                <td style="width: 150px;">{{ customer_obj.course }}</td>
                <td>{{ customer_obj.get_status_display }}</td>
                <td style="width: 160px;">{{ customer_obj.get_classlist|default:'----' }}</td>
                <td>{{ customer_obj.consultant.username|default:'----' }}</td>
                {% if 'morefollowrecord'|permission_arg:request %}
                    <td><a href="{% url 'morefollowrecord' customer_obj.pk %}">详情</a></td>
                {% endif %}
                {% if 'editmycustomer'|permission_arg:request or 'editcustomer'|permission_arg:request or 'deletemycustomer'|permission_arg:request or 'deletecustomer'|permission_arg:request %}
                    <td>
                        {% if flag %}
                            {% if 'editmycustomer'|permission_arg:request %}
                                <a href="{% url 'editmycustomer' customer_obj.pk %}" class="btn btn-warning btn-xs"
                                   title="编辑"><i class="fa fa-edit"></i></a>
                            {% endif %}
                        {% else %}
                            {% if 'editcustomer'|permission_arg:request %}
                                <a href="{% url 'editcustomer' customer_obj.pk %}" class="btn btn-warning btn-xs"
                                   title="编辑"><i
                                        class="fa fa-edit"></i></a>
                            {% endif %}
                        {% endif %}

                        {% if flag %}
                            {% if 'deletemycustomer'|permission_arg:request %}
                                <a href="{% url 'deletemycustomer' customer_obj.pk %}" class="btn btn-danger btn-xs"
                                   title="删除"><i class="fa fa-trash-o fa-lg"></i></a>
                            {% endif %}
                        {% else %}
                            {% if 'deletecustomer'|permission_arg:request %}
                                <a href="{% url 'deletecustomer' customer_obj.pk %}" class="btn btn-danger btn-xs"
                                   title="删除"><i class="fa fa-trash-o fa-lg"> </i></a>
                            {% endif %}
                        {% endif %}


                    </td>
                {% endif %}

            </tr>
        {% endfor %}

        </tbody>
    </table>
    {{ page|safe }}


{% endblock %}

<!--js代码-->
{% block js %}
    <script src="{% static 'jquery-cookie-1.4.1.js' %}"></script>
    <script>
        //全选操作
        $('#all').click(function () {
            $('input[name=select]').prop('checked', true);
        });
        //反选操作
        $('#opp').click(function () {
            var unchecked = $('input[name=select]:not(:checked)');
            $('input[name=select]:checked').prop('checked', false);
            unchecked.prop('checked', true)
        });


        //选择批量操作的条件
        $('#operation').change(function () {
            {#alert($('#operation').val());#}

            if ($('#operation').val() === 'batch_update') {
                $("#fields").attr('hidden', false);
            } else {
                $("#fields").attr('hidden', 'hidden');
                $('.c1').attr('hidden', 'hidden');
            }
        });

        $('#fields').change(function () {
            var id = "#" + $('#fields').val();
            $('.c1').attr('hidden', 'hidden');
            $(id).attr('hidden', false);
        });


        //批量处理提交
        $("#batch_operation").click(function () {
            var operation = $("#operation").val();//获取批量操作类型
            //alert(operation);
            var selecteds = $('input[name=select]:checked');//获取已选中的数据
            //console.log(selecteds);
            //循环获取选中数据的value值添加到数组
            var checked_id_list = [];
            selecteds.each(function (index, obj) {//注意值和索引的顺序
                //console.log(obj);
                //console.log(val);
                {#checked_id_list.push(obj.value);#}
                checked_id_list.push($(obj).val());//注意each循环出来都是dom对象
            });
            console.log(checked_id_list);
            console.log($("#" + $('#fields').val()).children('select').val());
            //  批量操作提交确认
            if (operation && checked_id_list.length) {

                if (confirm('确定执行吗？')) {
                    $.ajax({
                        url: {% if flag %}'{% url "mycustomers" %}'{% else %}'{% url "customers" %}'{% endif %},
                        type:
                            'post',
                        headers:
                            {
                                'X-CSRFToken':
                                    $.cookie('csrftoken')
                            }
                        ,
                        data: {
                            operation: operation,
                            id_list:
                                JSON.stringify(checked_id_list),
                            filed:
                                $('#fields').val(),
                            val:
                                $("#" + $('#fields').val()).children('select').val(),
                            //id_list:checked_id_list,
                        }
                        ,
                        success: function (response) {
                            var op = response.operaiton;
                            var status = response.status;
                            console.log(op);
                            console.log(status);
                            if (status === 1) {
                                if (op === 'batch_delete') {
                                    alert('批量删除成功！');
                                }
                                else if (op === 'batch_update') {
                                    alert('批量更新成功！');
                                }
                                else if (op === 'batch_public_private') {
                                    alert('公户转私户成功！');
                                }
                                else if (op === 'batch_private_public') {
                                    alert('私户转公户成功！');
                                }
                                ;

                                location.reload();
                            } else {
                                if (op !== '') {
                                    alert('批量操作失败！')
                                }
                            }


                        }
                        ,
                    })
                    ;
                }
                ;
            }


        });

    </script>



    <script>
        $('.c2').children().prop('disabled', 'disabled');
        $("#search").change(function () {
            var clas = "." + $("#search").val();
            $('.c2').prop('hidden', 'hidden');
            $('.c2').children().prop('disabled', 'disabled');
            $(clas).prop('hidden', false);
            $(clas).children().prop('disabled', false);
        });
    </script>
{% endblock %}